//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlienGames.Web.PlayedGame {
    
    
    public partial class CurrentGame {
        
        /// <summary>
        /// ChatController control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SlienGames.Web.CustomControlls.Chat.ChatController ChatController;
    }
}
